services:
  latex-editor:
    build:
      context: .
    volumes:
      - ../:/workspace
      # SSH directory
      - ~/.ssh:/root/.ssh
      # Git config
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity
